--drop table public.gameinfo

CREATE TABLE PUBLIC.GAMEINFO
(TS TIMESTAMP NOT NULL,
METHOD_NAME CHAR(50) NOT NULL, 
PLAYER_ID DECIMAL(10,2) NOT NULL,
TRANSFER_OBJECT CHAR(200000) NOT NULL,
PRIMARY KEY (TS))
